<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Configuration\Configuration.csproj" />
    <ProjectReference Include="..\DbContext\DbContext.csproj" />
    <ProjectReference Include="..\DbRepos\DbRepos.csproj" />
    <ProjectReference Include="..\Encryptions\Encryptions.csproj" />
    <ProjectReference Include="..\Models\Models.csproj" />
    <ProjectReference Include="..\Services\Services.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
